services:
  backend:
    build: ./smartdesk-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SECURITY_ACCESS_TOKEN_SECRET: ${SECURITY_ACCESS_TOKEN_SECRET:-QuestaEunaChiaveSuperSegretaMoltoLungaPerGarantireLaSicurezzaDeiToken123!}
      ALLOWED_ORIGINS: http://localhost
    volumes:
      - backend-data:/app/data

  frontend:
    build: ./smartdesk-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend-data:
